export const WIDGET_TYPES = {
  SYSTEM_STATUS: 'SYSTEM_STATUS',
  SWAP_CURVES: 'SWAP_CURVES',
  SQ_DATENBAUM: 'SQ_DATENBAUM',
  TX_DATENBAUM: 'TX_DATENBAUM',
  SCHEDULING: 'SCHEDULING',
  RSX_BOTTOM_UP: 'RSX_BOTTOM_UP',
  KURS: 'KURS',
  GRUPPE: 'GRUPPE',
  GOVI_CURVES: 'GOVI_CURVES',
  CHECK_SCORE_CARD: 'CHECK_SCORE_CARD',
};

export const WIDGET_TITLES = {
  [WIDGET_TYPES.SYSTEM_STATUS]: 'SYSTEM STATUS',
  [WIDGET_TYPES.SWAP_CURVES]: 'SWAP CURVES',
  [WIDGET_TYPES.SQ_DATENBAUM]: 'DATENBAUM',
  [WIDGET_TYPES.TX_DATENBAUM]: 'DATENBAUM',
  [WIDGET_TYPES.SCHEDULING]: 'SCHEDULING',
  [WIDGET_TYPES.RSX_BOTTOM_UP]: 'BOTTOM UP',
  [WIDGET_TYPES.KURS]: 'KURS-WÄHRUNG & ALLOKATIONSFAKTOR',
  [WIDGET_TYPES.GRUPPE]: 'GRUPPE I & II',
  [WIDGET_TYPES.GOVI_CURVES]: 'GOVI CURVES',
  [WIDGET_TYPES.CHECK_SCORE_CARD]: 'CHECK SCORECARD',
};

export const WIDGET_WITH_SUB_ITEMS = 'WIDGET_WITH_SUB_ITEMS';

export const LEFT_BLOCK_DEFAULT_WIDGETS = [
  WIDGET_TYPES.SYSTEM_STATUS,
  WIDGET_TYPES.TX_DATENBAUM,
  WIDGET_TYPES.SQ_DATENBAUM,
  WIDGET_TYPES.RSX_BOTTOM_UP,
];

export const CENTER_BLOCK_DEFAULT_WIDGETS = [
  WIDGET_TYPES.SWAP_CURVES,
  WIDGET_TYPES.GOVI_CURVES,
  WIDGET_TYPES.KURS,
  WIDGET_TYPES.CHECK_SCORE_CARD,
];

export const CENTER_TOP_DEFAULT_WIDGETS = [
  WIDGET_TYPES.SWAP_CURVES,
  WIDGET_TYPES.GOVI_CURVES,
  WIDGET_TYPES.KURS,
];

export const CENTER_BOTTOM_DEFAULT_WIDGETS = [
  WIDGET_TYPES.CHECK_SCORE_CARD,
];

export const RIGHT_BLOCK_DEFAULT_WIDGETS = [
  WIDGET_TYPES.GRUPPE,
  WIDGET_TYPES.SCHEDULING,
];
